### ISSUE TITLE
predict just one sample

### ISSUE THREAD

**Issue by ak-karimzai** [clovaai/aasist#11]
is it possible to test pretrained model only with one sample (to detect that its spoofed or bona-fide)?
i mean, how to eval or test pretrained models in sample machine, which don't have best hardware resources.

**Comment by Jungjee** [comment]
Hi @ak-karimzai, yes it would be possible. But you would need to modify the code a bit for this.

**Comment by MindVu** [comment]
Hi, I would love to know if you have tackled this problem?

**Comment by djanito** [comment]
Hey, would be really interested into knowing how to evaluate one sample using the pretrained model
