### ISSUE TITLE
How to Use Feature Extraction Methods

### ISSUE THREAD

**Issue by ahmed-sevimli** [clovaai/aasist#13]
I would like to try using MFCC/LFCC and other feature extraction methods in this project.

- Is it possible to do so without changing much?

- And if you could guide me on how to do it please?

@Jungjee @hsss

**Comment by Jungjee** [comment]
Hi @ahmed-sevimli, I believe you can start by replacing the conv module here. https://github.com/clovaai/aasist/blob/a04c9863f63d44471dde8a6abcb3b082b07cd1d1/models/AASIST.py#L479 

This module derives a feature map directly from a raw waveform input. You can replace them with acoustic features such as MFCC.
