### ISSUE TITLE
Can not reproduce result

### ISSUE THREAD

**Issue by gandolfxu** [clovaai/aasist#5]
In the paper, the best EER is 0.83. I can get this result with pretrained model.

I can't reproduce this result if I train with default setting and then test with this model.

I excutate commands in th following:
1. python main.py --config ./config/AASIST.conf
2. python main.py --eval --config ./config/AASIST.conf

In the second step, I configure "model_path" to my model.

The EER in my experiment is 2.148, and min t-DCF is 0.07

**Comment by gandolfxu** [comment]
I found the model size of pretained model is 1281532, and mine is 1275639

**Comment by sasv-challenge** [comment]
Hello @gandolfxu, 
did you match the training environment that is shared in the ReadME?

**Comment by Jungjee** [comment]
Hello @gandolfxu,
did you match the training environment specifications in `ReadMe.md`?

**Comment by Jungjee** [comment]
Closing temporarily. @gandolfxu, please re-open this issue when you want.
