### ISSUE TITLE
somthing confusing

### ISSUE THREAD

**Issue by wtl-lang** [clovaai/aasist#6]
https://github.com/clovaai/aasist/blob/a04c9863f63d44471dde8a6abcb3b082b07cd1d1/models/AASIST.py#L453

Why on the right of this expression you use 'x' instead of 'out'? When you use 'out = self.conv1(x)', the 'if-else' is nonsense.

**Comment by Jungjee** [comment]
Hi @wtl-lang.
You are right. This is an error.

Line 453 should be `out = self.conv1(out)` as you said.

However, changing this would make pre-trained weights useless; hence I will leave this a known issue for now. 

Thank you for reporting this issue :-)
